import { getSiteUrl } from "@/lib/seo";
import { SeoConfig } from "@/types/SeoTypes";

// System / oauth pages — no indexing
export const SYSTEM_PATHS = [
  "/verify",
  "/auth/callback",
  "/cli-auth",
  "/auth/github",
  "/auth/gitlab",
  "/auth/bitbucket",
  "/auth/azure",
  "/github/oauth/complete",
  "/gitlab/oauth/complete",
  "/bitbucket/oauth/complete",
  "/azure/oauth/complete",
  "/forgot-password",
  "/reset-password",
];

export const MARKETING_KEYWORDS = [
  "ai documentation",
  "developer documentation",
  "github documentation generator",
  "auto-generate docs from code",
  "codebase documentation",
  "api documentation tool",
  "multi-agent ai",
  "docnine",
  "docnine ai",
  "documentation generator",
  "keep docs in sync",
  "Docnine AI",
  "generate documentation from code",
  "docnine",
  "docnine documentation",
  "docnine ai documentation",
  "ai code documentation",
  "automated api docs",
  "dev docs generator",
  "code to docs ai",
  "documentation automation",
  "ai dev docs",
  "codebase to docs",
  "github docs generator",
  "code documentation ai",
  "ai documentation tool",
  "developer docs ai",
  "codebase documentation ai",
  "ai generated docs",
  "auto documentation tool",
  "code documentation software",
  "documentation ai tool",
  "ai documentation generator",
  "developer documentation ai",
  "code to documentation ai",
  "ai documentation assistant",
  "codebase to documentation",
  "ai docs generator",
  "documentation from code",
  "ai code docs",
  "code documentation tool",
  "ai documentation software",
  "documentation generation ai",
  "ai documentation platform",
  "code documentation ai tool",
  "ai documentation system",
  "documentation ai software",
  "ai documentation app",
  "code documentation ai platform",
  "ai documentation solution",
  "documentation ai generator",
  "ai documentation builder",
  "code documentation ai software",
  "ai documentation creation tool",
  "documentation ai platform",
  "ai documentation automation tool",
  "code documentation ai solution",
  "ai documentation generation software",
  "documentation ai automation",
  "ai documentation writing tool",
  "code documentation ai automation",
  "ai documentation maintenance tool",
  "documentation ai maintenance",
  "ai documentation sync tool",
  "code documentation ai sync",
  "ai documentation update tool",
  "documentation ai update",
  "ai documentation version control",
  "code documentation ai versioning",
  "ai documentation collaboration tool",
  "documentation ai collaboration",
  "ai documentation sharing tool",
  "code documentation ai sharing",
  "ai documentation publishing tool",
  "documentation ai publishing",
  "ai documentation export tool",
  "code documentation ai export",
  "ai documentation template tool",
  "documentation ai templates",
  "ai documentation customization tool",
  "code documentation ai customization",
  "ai documentation styling tool",
  "documentation ai styling",
  "ai documentation formatting tool",
  "code documentation ai formatting",
  "ai documentation structure tool",
  "documentation ai structure",
  "ai documentation navigation tool",
  "code documentation ai navigation",
  "ai documentation search tool",
  "documentation ai search",
  "ai documentation tagging tool",
  "code documentation ai tagging",
  "ai documentation metadata tool",
];

export const AUTH_KEYWORDS = [
  "docnine login",
  "docnine signup",
  "developer documentation tool",
  "docnine authentication",
  "docnine auth",
  "sign into docnine",
  "create docnine account",
  "docnine",
  "docnine documentation",
];

const siteUrl = getSiteUrl();

export const PUBLIC_PAGES: Record<string, SeoConfig> = {
  "/": {
    title: "Docnine -  AI Documentation for Engineering Teams",
    description:
      "Ship better documentations, faster. Stop writing documentation by hand. Create and maintain developer documentation with AI. Docnine generates docs from your codebase, then keeps them up to date as your code evolves.",
    pathname: "/",
    keywords: MARKETING_KEYWORDS,
    appendSiteName: false,
    imageWidth: 1200,
    imageHeight: 630,
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "Docnine",
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Web",
      url: siteUrl,
      description:
        "Generate, publish, and maintain developer documentation from code with AI.",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
        availability: "https://schema.org/InStock",
      },
    },
  },
  "/login": {
    title: "Sign In To Your Account",
    description:
      "Sign in to Docnine to generate, publish, and maintain documentation for your codebase — automatically.",
    pathname: "/login",
    keywords: AUTH_KEYWORDS,
    robots: "index, follow",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Sign In to Docnine",
      url: `${siteUrl}/login`,
      description: "Secure sign-in to the Docnine documentation platform.",
    },
  },
  "/signup": {
    title: "Create a Free Account",
    description:
      "Get started with Docnine for free. Connect your repo and generate your first documentation in minutes.",
    pathname: "/signup",
    keywords: [
      ...AUTH_KEYWORDS,
      "free developer documentation",
      "docnine free plan",
      "github docs generator free",
    ],
    robots: "index, follow",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Sign Up for Docnine",
      url: `${siteUrl}/signup`,
      description:
        "Create a free Docnine account to auto-generate documentation from your codebase.",
    },
  },
  "/pricing": {
    title: "Pricing Plans",
    description:
      "Start free, then scale. Compare Docnine plans for solo developers and teams — including unlimited projects, security audits, and shared portals.",
    pathname: "/pricing",
    keywords: [
      ...MARKETING_KEYWORDS,
      "documentation pricing",
      "developer tools pricing",
      "docnine free plan",
      "docnine pro",
    ],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Docnine Pricing",
      url: `${siteUrl}/pricing`,
      description:
        "Pricing and plan comparison for Docnine's AI documentation platform.",
    },
  },
  "/docs": {
    title: "Platform Documentation",
    description:
      "Everything you need to set up Docnine: GitHub integration, webhooks, AI agent workflows, public portals, exports, and billing.",
    pathname: "/docs",
    keywords: [
      ...MARKETING_KEYWORDS,
      "docnine docs",
      "docnine setup guide",
      "github webhook documentation",
      "how to use docnine",
    ],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "TechArticle",
      headline: "Docnine Platform Documentation",
      url: `${siteUrl}/docs`,
      description:
        "Official setup and usage guide for the Docnine documentation platform.",
      author: { "@type": "Organization", name: "Docnine", url: siteUrl },
    },
  },
  "/contact": {
    title: "Contact Us",
    description:
      "Reach the Docnine team for support, feature requests, enterprise pricing, or partnership enquiries.",
    pathname: "/contact",
    keywords: ["contact docnine", "docnine support", "docnine enterprise"],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "ContactPage",
      name: "Contact Docnine",
      url: `${siteUrl}/contact`,
    },
  },
  "/terms": {
    title: "Terms and Conditions",
    description:
      "Review Docnine's terms and conditions — account usage, service limits, data handling, and your legal rights.",
    pathname: "/terms",
    keywords: ["docnine terms", "terms and conditions", "docnine legal"],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Docnine Terms and Conditions",
      url: `${siteUrl}/terms`,
    },
  },
  "/privacy": {
    title: "Privacy Policy",
    description:
      "Learn how Docnine collects, uses, and safeguards your account data, repository contents, and product usage information.",
    pathname: "/privacy",
    keywords: ["docnine privacy", "privacy policy", "data protection", "GDPR"],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Docnine Privacy Policy",
      url: `${siteUrl}/privacy`,
    },
  },
};
