import { getSiteUrl } from "@/lib/seo";
import { SeoConfig } from "@/types/SeoTypes";

// System / oauth pages : no indexing
export const SYSTEM_PATHS = [
  "/verify",
  "/auth/callback",
  "/cli-auth",
  "/auth/github",
  "/auth/gitlab",
  "/auth/bitbucket",
  "/auth/azure",
  "/github/oauth/complete",
  "/gitlab/oauth/complete",
  "/bitbucket/oauth/complete",
  "/azure/oauth/complete",
  "/forgot-password",
  "/reset-password",
];

export const MARKETING_KEYWORDS = [
  "ai documentation",
  "developer documentation",
  "github documentation generator",
  "auto-generate docs from code",
  "codebase documentation",
  "api documentation tool",
  "multi-agent ai",
  "docnine",
  "docnine ai",
  "documentation generator",
  "keep docs in sync",
  "Docnine AI",
  "generate documentation from code",
  "docnine",
  "docnine documentation",
  "docnine ai documentation",
  "ai code documentation",
  "automated api docs",
  "dev docs generator",
  "code to docs ai",
  "documentation automation",
  "ai dev docs",
  "codebase to docs",
  "github docs generator",
  "code documentation ai",
  "ai documentation tool",
  "developer docs ai",
  "codebase documentation ai",
  "ai generated docs",
  "auto documentation tool",
  "code documentation software",
  "documentation ai tool",
  "ai documentation generator",
  "developer documentation ai",
  "code to documentation ai",
  "ai documentation assistant",
  "codebase to documentation",
  "ai docs generator",
  "documentation from code",
  "ai code docs",
  "code documentation tool",
  "ai documentation software",
  "documentation generation ai",
  "ai documentation platform",
  "code documentation ai tool",
  "ai documentation system",
  "documentation ai software",
  "ai documentation app",
  "code documentation ai platform",
  "ai documentation solution",
  "documentation ai generator",
  "ai documentation builder",
  "code documentation ai software",
  "ai documentation creation tool",
  "documentation ai platform",
  "ai documentation automation tool",
  "code documentation ai solution",
  "ai documentation generation software",
  "documentation ai automation",
  "ai documentation writing tool",
  "code documentation ai automation",
  "ai documentation maintenance tool",
  "documentation ai maintenance",
  "ai documentation sync tool",
  "code documentation ai sync",
  "ai documentation update tool",
  "documentation ai update",
  "ai documentation version control",
  "code documentation ai versioning",
  "ai documentation collaboration tool",
  "documentation ai collaboration",
  "ai documentation sharing tool",
  "code documentation ai sharing",
  "ai documentation publishing tool",
  "documentation ai publishing",
  "ai documentation export tool",
  "code documentation ai export",
  "ai documentation template tool",
  "documentation ai templates",
  "ai documentation customization tool",
  "code documentation ai customization",
  "ai documentation styling tool",
  "documentation ai styling",
  "ai documentation formatting tool",
  "code documentation ai formatting",
  "ai documentation structure tool",
  "documentation ai structure",
  "ai documentation navigation tool",
  "code documentation ai navigation",
  "ai documentation search tool",
  "documentation ai search",
  "ai documentation tagging tool",
  "code documentation ai tagging",
  "ai documentation metadata tool",
];

export const AUTH_KEYWORDS = [
  "docnine login",
  "docnine signup",
  "developer documentation tool",
  "docnine authentication",
  "docnine auth",
  "sign into docnine",
  "create docnine account",
  "docnine",
  "docnine documentation",
];

const siteUrl = getSiteUrl();

export const PUBLIC_PAGES: Record<string, SeoConfig> = {
  "/": {
    title: "Docnine , AI documentation for engineering teams",
    description:
      "Generate clear developer docs from your codebase and keep them up to date as your code changes. Less busywork, better documentation.",
    pathname: "/",
    keywords: MARKETING_KEYWORDS,
    appendSiteName: false,
    imageWidth: 1200,
    imageHeight: 630,
    structuredData: {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "Docnine",
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Web",
      url: siteUrl,
      description:
        "Generate and maintain developer documentation from your code with AI.",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
        availability: "https://schema.org/InStock",
      },
    },
  },
  "/login": {
    title: "Sign in",
    description:
      "Sign in to Docnine to generate and maintain documentation for your codebase.",
    pathname: "/login",
    keywords: AUTH_KEYWORDS,
    robots: "index, follow",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Sign in to Docnine",
      url: `${siteUrl}/login`,
      description: "Sign in to your Docnine account.",
    },
  },
  "/signup": {
    title: "Create a free account",
    description:
      "Create a free Docnine account, connect a repo, and generate your first docs in minutes.",
    pathname: "/signup",
    keywords: [
      ...AUTH_KEYWORDS,
      "free developer documentation",
      "docnine free plan",
      "github docs generator free",
    ],
    robots: "index, follow",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Sign up for Docnine",
      url: `${siteUrl}/signup`,
      description:
        "Create a free Docnine account to generate documentation from your codebase.",
    },
  },
  "/pricing": {
    title: "Pricing",
    description:
      "Start free, then upgrade when you need more. Compare Docnine plans for individuals and teams.",
    pathname: "/pricing",
    keywords: [
      ...MARKETING_KEYWORDS,
      "documentation pricing",
      "developer tools pricing",
      "docnine free plan",
      "docnine pro",
    ],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Docnine Pricing",
      url: `${siteUrl}/pricing`,
      description:
        "Pricing and plan comparison for Docnine.",
    },
  },
  "/docs": {
    title: "Documentation",
    description:
      "Guides for setting up Docnine , GitHub, webhooks, AI workflows, portals, exports, and billing.",
    pathname: "/docs",
    keywords: [
      ...MARKETING_KEYWORDS,
      "docnine docs",
      "docnine setup guide",
      "github webhook documentation",
      "how to use docnine",
    ],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "TechArticle",
      headline: "Docnine documentation",
      url: `${siteUrl}/docs`,
      description:
        "Setup guides and reference docs for Docnine.",
      author: { "@type": "Organization", name: "Docnine", url: siteUrl },
    },
  },
  "/contact": {
    title: "Contact us",
    description:
      "Questions, feedback, or partnership ideas? Reach the Docnine team.",
    pathname: "/contact",
    keywords: ["contact docnine", "docnine support", "docnine enterprise"],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "ContactPage",
      name: "Contact Docnine",
      url: `${siteUrl}/contact`,
    },
  },
  "/terms": {
    title: "Terms of use",
    description:
      "Terms that govern your use of Docnine.",
    pathname: "/terms",
    keywords: ["docnine terms", "terms and conditions", "docnine legal"],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Docnine Terms of Use",
      url: `${siteUrl}/terms`,
    },
  },
  "/privacy": {
    title: "Privacy policy",
    description:
      "How Docnine collects, uses, and protects your information.",
    pathname: "/privacy",
    keywords: ["docnine privacy", "privacy policy", "data protection", "GDPR"],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Docnine Privacy Policy",
      url: `${siteUrl}/privacy`,
    },
  },
};
